stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the Docker image..."
    - docker build -t nadinsoft-api .

test:
  stage: test
  script:
    - echo "Running dummy tests..."
    - docker run --rm -d -p 5000:5000 --name test-api nadinsoft-api
    - sleep 3
    - curl -f http://localhost:5000 || exit 1
    - docker stop test-api

deploy:
  stage: deploy
  script:
    - echo "Deploying with Docker Compose..."
    - docker-compose up -d
